{"abstract":[{"text":"This guide describes how to get started with VietnameseInput.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vietnameseinput\/getting-started-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/vietnameseinput\/getting-started-article"]}],"primaryContentSections":[{"content":[{"anchor":"Setting-up-the-SDK","level":2,"text":"Setting up the SDK","type":"heading"},{"inlineContent":[{"type":"text","text":"This SDK requires a "},{"identifier":"https:\/\/kankoda.com\/vietnameseinput","type":"reference","isActive":true},{"type":"text","text":" to be used. You can sign up for a license from the "},{"overridingTitle":"product website","identifier":"https:\/\/kankoda.com\/vietnameseinput","overridingTitleInlineContent":[{"type":"text","text":"product website"}],"type":"reference","isActive":true},{"type":"text","text":" or "},{"identifier":"https:\/\/kankoda.gumroad.com","type":"reference","isActive":true},{"type":"text","text":", then use the "},{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInput\/setupLicense(withLicenseKey:productBundle:)","type":"reference","isActive":true},{"type":"text","text":" function to unlock the SDK with your license:"}],"type":"paragraph"},{"syntax":"swift","code":["let license = try await VietnameseInput.setupLicense(","    licenseKey: \"abc-123\",  \/\/ If you have a VietnameseInput license key","    productBundle: .module  \/\/ If you have a VietnameseInput license file",")"],"type":"codeListing"},{"inlineContent":[{"text":"If you have a yearly business or enterprise license and have a ","type":"text"},{"code":"VietnameseInput.license","type":"codeVoice"},{"text":" file, you can remove the ","type":"text"},{"code":"licenseKey","type":"codeVoice"},{"text":" parameter and instead provide the bundle in which this file exists.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This function will return your license or throw an error. You can use the license or the global "},{"type":"reference","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInput\/currentLicense","isActive":true},{"type":"text","text":" to inspect your license."}],"type":"paragraph"},{"style":"tip","content":[{"type":"paragraph","inlineContent":[{"text":"You can use the “FREE” license key to set up the library with a capped license that can make 50 requests before it stops working.","type":"text"}]}],"name":"Tip","type":"aside"},{"anchor":"Namespaces","level":2,"text":"Namespaces","type":"heading"},{"inlineContent":[{"text":"This library has a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese","isActive":true},{"text":" namespace with language-related models like ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/Diacritic","isActive":true},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod","isActive":true},{"text":", and a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInput","isActive":true},{"text":" namespace with library- and license-related models.","type":"text"}],"type":"paragraph"},{"anchor":"Vietnamese-Input-Engine","level":2,"text":"Vietnamese Input Engine","type":"heading"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputEngine","type":"reference"},{"text":" type can be used for Vietnamese input. To use it, create an instance after registering your license:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["let engine = try VietnameseInputEngine()        \/\/ Fails if no license is registered"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"This engine supports both "},{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod\/telex","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod\/viqr","isActive":true,"type":"reference"},{"type":"text","text":", and "},{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod\/vni","isActive":true,"type":"reference"},{"type":"text","text":". You can see "},{"identifier":"https:\/\/vntyping.com","isActive":true,"type":"reference"},{"type":"text","text":" for more information on how these "},{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod","isActive":true,"type":"reference"},{"type":"text","text":"s work."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"With the engine in place, you can use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputEngine\/input(_:into:with:)"},{"type":"text","text":" to simulate typing a sequence of characters into a text."}],"type":"paragraph"},{"syntax":"swift","code":["\/\/ TELEX","engine.input(\"uow\", into: \"\", with: .telex)     \/\/ -> \"ươ\"","engine.input(\"ow\", into: \"u\", with: .telex)     \/\/ -> \"ươ\"","engine.input(\"Duowng\", into: \"\", with: .telex)  \/\/ -> \"Dương\"","","\/\/ VIQR","engine.input(\"uo*\",in to: \"\", with: .viqr)      \/\/ -> \"ươ\"","engine.input(\"o*\",in to: \"u\", with: .viqr)      \/\/ -> \"ươ\"","engine.input(\"Duo*ng\"in, to: \"\", with: .viqr)   \/\/ -> \"Dương\"","","\/\/ VNI","engine.input(\"uo7\", into: \"\", with: .vni)       \/\/ -> \"ươ\"","engine.input(\"o7\", into: \"u\", with: .vni)       \/\/ -> \"ươ\"","engine.input(\"Duo7ng\", into: \"\", with: .vni)    \/\/ -> \"Dương\""],"type":"codeListing"},{"inlineContent":[{"text":"You can also use the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputEngine\/diacriticReplacement(whenInputting:into:with:)","type":"reference"},{"text":" function to see if an input character should be replaced with a diacritic, and if so how.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"VietnameseInput"}],"title":"Getting Started","roleHeading":"Article","role":"article"},"identifier":{"url":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Getting-Started-Article","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput"]]},"sections":[],"references":{"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInputEngine":{"type":"topic","abstract":[{"type":"text","text":"This Vietnamese input engine can be used simulate typing"},{"type":"text","text":" "},{"type":"text","text":"text with any supported "},{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VietnameseInputEngine"}],"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputEngine","title":"VietnameseInputEngine","kind":"symbol","url":"\/documentation\/vietnameseinput\/vietnameseinputengine","navigatorTitle":[{"kind":"identifier","text":"VietnameseInputEngine"}]},"https://vntyping.com":{"title":"this page","url":"https:\/\/vntyping.com","titleInlineContent":[{"type":"text","text":"this page"}],"identifier":"https:\/\/vntyping.com","type":"link"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInputEngine/input(_:into:with:)":{"type":"topic","role":"symbol","url":"\/documentation\/vietnameseinput\/vietnameseinputengine\/input(_:into:with:)","title":"input(_:into:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"input","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Vietnamese","kind":"typeIdentifier","preciseIdentifier":"s:15VietnameseInput0A0V"},{"text":".","kind":"text"},{"text":"InputMethod","kind":"typeIdentifier","preciseIdentifier":"s:15VietnameseInput0A0V0B6MethodO"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputEngine\/input(_:into:with:)","abstract":[{"text":"Append a sequence of characters to the provided text.","type":"text"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Vietnamese/InputMethod/vni":{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod\/vni","url":"\/documentation\/vietnameseinput\/vietnamese\/inputmethod\/vni","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vni","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"VNI uses number & function characters to apply diacritics."}],"title":"Vietnamese.InputMethod.vni"},"https://kankoda.com/vietnameseinput":{"title":"valid SDK license","url":"https:\/\/kankoda.com\/vietnameseinput","titleInlineContent":[{"type":"text","text":"valid SDK license"}],"identifier":"https:\/\/kankoda.com\/vietnameseinput","type":"link"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInput":{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInput","abstract":[{"type":"text","text":"A namespace for SDK-related features."}],"url":"\/documentation\/vietnameseinput\/vietnameseinput","type":"topic","title":"VietnameseInput","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VietnameseInput","kind":"identifier"}],"navigatorTitle":[{"text":"VietnameseInput","kind":"identifier"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Vietnamese/Diacritic":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/vietnameseinput\/vietnamese\/diacritic","title":"Vietnamese.Diacritic","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/Diacritic","abstract":[{"text":"This type represents a Vietnamese diacritic.","type":"text"}],"navigatorTitle":[{"text":"Diacritic","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Diacritic","kind":"identifier"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput":{"title":"VietnameseInput","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput","role":"collection","abstract":[{"type":"text","text":"Add Vietnamese input to your apps on all major Apple platforms."}],"url":"\/documentation\/vietnameseinput","kind":"symbol","type":"topic"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Vietnamese":{"abstract":[{"text":"A namespace for Vietnamese language features.","type":"text"}],"url":"\/documentation\/vietnameseinput\/vietnamese","role":"symbol","type":"topic","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Vietnamese","kind":"identifier"}],"navigatorTitle":[{"text":"Vietnamese","kind":"identifier"}],"kind":"symbol","title":"Vietnamese"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInput/currentLicense":{"type":"topic","role":"symbol","url":"\/documentation\/vietnameseinput\/vietnameseinput\/currentlicense","title":"currentLicense","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentLicense","kind":"identifier"},{"text":": ","kind":"text"},{"text":"License","kind":"typeIdentifier","preciseIdentifier":"s:15VietnameseInputAAV7Licensea"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInput\/currentLicense","abstract":[{"text":"The currently registered license, if any.","type":"text"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInputEngine/diacriticReplacement(whenInputting:into:with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diacriticReplacement","kind":"identifier"},{"text":"(","kind":"text"},{"text":"whenInputting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Vietnamese","preciseIdentifier":"s:15VietnameseInput0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"InputMethod","preciseIdentifier":"s:15VietnameseInput0A0V0B6MethodO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Vietnamese","preciseIdentifier":"s:15VietnameseInput0A0V","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DiacriticReplacement","preciseIdentifier":"s:15VietnameseInput0A0V20DiacriticReplacementV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputEngine\/diacriticReplacement(whenInputting:into:with:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Get which diacritic replacement, if any, to use when"},{"type":"text","text":" "},{"type":"text","text":"inputting a single character into a text."}],"url":"\/documentation\/vietnameseinput\/vietnameseinputengine\/diacriticreplacement(wheninputting:into:with:)","title":"diacriticReplacement(whenInputting:into:with:)","kind":"symbol"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Vietnamese/InputMethod":{"url":"\/documentation\/vietnameseinput\/vietnamese\/inputmethod","kind":"symbol","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputMethod"}],"title":"Vietnamese.InputMethod","abstract":[{"text":"This enum defines available Vietnamese input methods.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"InputMethod"}]},"https://kankoda.gumroad.com":{"type":"link","title":"license store","url":"https:\/\/kankoda.gumroad.com","identifier":"https:\/\/kankoda.gumroad.com","titleInlineContent":[{"type":"text","text":"license store"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Vietnamese/InputMethod/telex":{"url":"\/documentation\/vietnameseinput\/vietnamese\/inputmethod\/telex","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod\/telex","type":"topic","abstract":[{"text":"TELEX uses alphabetic characters to apply diacritics.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"telex","kind":"identifier"}],"title":"Vietnamese.InputMethod.telex","role":"symbol","kind":"symbol"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Vietnamese/InputMethod/viqr":{"kind":"symbol","type":"topic","role":"symbol","title":"Vietnamese.InputMethod.viqr","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod\/viqr","url":"\/documentation\/vietnameseinput\/vietnamese\/inputmethod\/viqr","abstract":[{"text":"VIQR uses punctuation characters to apply diacritics.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viqr"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInput/setupLicense(withLicenseKey:productBundle:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupLicense","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLicenseKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"productBundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"License","preciseIdentifier":"s:15VietnameseInputAAV7Licensea","kind":"typeIdentifier"}],"title":"setupLicense(withLicenseKey:productBundle:)","url":"\/documentation\/vietnameseinput\/vietnameseinput\/setuplicense(withlicensekey:productbundle:)","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInput\/setupLicense(withLicenseKey:productBundle:)","abstract":[{"type":"text","text":"Set up the SDK with a license key, or a license file."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}