{"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"type":"image","identifier":"Logo"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"VietnameseInput is a Swift SDK that can be used to add Vietnamese TELEX, VNI, and VIQR input support to your apps on major Apple platforms (iOS, macOS, tvOS, watchOS & visionOS)."}],"type":"paragraph"},{"inlineContent":[{"text":"VietnameseInput lets you type in TELEX, VNI, and VIQR, without having to switch to a Vietnamese keyboard. This can be useful in many different kind of applications, like games, educational apps, keyboard extensions, etc.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Pricing","anchor":"Pricing","type":"heading"},{"inlineContent":[{"text":"This package requires a commercial license to be used. You can sign up for a license from the ","type":"text"},{"isActive":true,"identifier":"https:\/\/kankoda.com\/vietnameseinput","type":"reference"},{"text":" or the ","type":"text"},{"isActive":true,"identifier":"https:\/\/kankoda.gumroad.com","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You can also use the “FREE” license key when setting up the library, as described in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Getting-Started-Article","type":"reference"},{"text":". This gives you access to a capped version of the library, that can make at most 50 input engine requests before it stops working.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Installation","anchor":"Installation","type":"heading"},{"inlineContent":[{"text":"VietnameseInput can be installed with the Swift Package Manager:","type":"text"}],"type":"paragraph"},{"syntax":null,"code":["https:\/\/github.com\/Kankoda\/VietnameseInput.git"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"This is a binary package, and must therefore only be linked to the main app target. All oher targets can still import & use it."}],"type":"paragraph"},{"level":2,"text":"Getting Started","anchor":"Getting-Started","type":"heading"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Getting-Started-Article","isActive":true},{"type":"text","text":" article describes how to get started with the VietnameseInput package and use some of its most essential features."}],"type":"paragraph"},{"level":2,"text":"Contact","anchor":"Contact","type":"heading"},{"inlineContent":[{"type":"text","text":"VietnameseInput is developed by "},{"isActive":true,"type":"reference","identifier":"https:\/\/kankoda.com"},{"type":"text","text":" in Stockholm, Sweden."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Website: "},{"type":"reference","isActive":true,"identifier":"https:\/\/kankoda.com\/vietnameseinput","overridingTitleInlineContent":[{"type":"text","text":"kankoda.com\/VietnameseInput"}],"overridingTitle":"kankoda.com\/VietnameseInput"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"E-mail: "},{"identifier":"mailto:info@kankoda.com","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Bluesky: "},{"type":"reference","identifier":"https:\/\/bsky.app\/profile\/kankoda.bsky.social","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Mastodon: "},{"type":"reference","identifier":"https:\/\/techhub.social\/@kankoda","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Feel free to reach out if you have any questions or feedback, or if you need support."}],"type":"paragraph"},{"level":2,"text":"Repository","anchor":"Repository","type":"heading"},{"inlineContent":[{"type":"text","text":"For more information, demo apps, issue tracking, etc., visit the "},{"type":"reference","identifier":"https:\/\/github.com\/Kankoda\/Vietnamese","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"level":2,"text":"License","anchor":"License","type":"heading"},{"inlineContent":[{"type":"text","text":"This package requires a commercial license to be used. You can sign up for a license from the "},{"type":"reference","overridingTitleInlineContent":[{"type":"text","text":"product website"}],"overridingTitle":"product website","isActive":true,"identifier":"https:\/\/kankoda.com\/vietnameseinput"},{"type":"text","text":" or the "},{"type":"reference","overridingTitleInlineContent":[{"text":"Gumroad store","type":"text"}],"overridingTitle":"Gumroad store","isActive":true,"identifier":"https:\/\/kankoda.gumroad.com"},{"type":"text","text":"."}],"type":"paragraph"}]}],"topicSections":[{"anchor":"Essentials","identifiers":["doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese","doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInput","doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputEngine"],"title":"Essentials"},{"anchor":"Articles","identifiers":["doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Getting-Started-Article"],"generated":true,"title":"Articles"},{"anchor":"Extended-Modules","identifiers":["doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/LicenseKit","doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Swift"],"generated":true,"title":"Extended Modules"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vietnameseinput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/vietnameseinput"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput"},"kind":"symbol","metadata":{"modules":[{"name":"VietnameseInput"}],"symbolKind":"module","roleHeading":"Framework","title":"VietnameseInput","externalID":"VietnameseInput","role":"collection"},"hierarchy":{"paths":[[]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Add Vietnamese input to your apps on all major Apple platforms."}],"references":{"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Vietnamese":{"abstract":[{"text":"A namespace for Vietnamese language features.","type":"text"}],"url":"\/documentation\/vietnameseinput\/vietnamese","role":"symbol","type":"topic","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Vietnamese","kind":"identifier"}],"navigatorTitle":[{"text":"Vietnamese","kind":"identifier"}],"kind":"symbol","title":"Vietnamese"},"https://kankoda.com/vietnameseinput":{"titleInlineContent":[{"text":"product website","type":"text"}],"url":"https:\/\/kankoda.com\/vietnameseinput","type":"link","identifier":"https:\/\/kankoda.com\/vietnameseinput","title":"product website"},"https://github.com/Kankoda/Vietnamese":{"type":"link","url":"https:\/\/github.com\/Kankoda\/Vietnamese","title":"project repository","identifier":"https:\/\/github.com\/Kankoda\/Vietnamese","titleInlineContent":[{"text":"project repository","type":"text"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInput":{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInput","abstract":[{"type":"text","text":"A namespace for SDK-related features."}],"url":"\/documentation\/vietnameseinput\/vietnameseinput","type":"topic","title":"VietnameseInput","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VietnameseInput","kind":"identifier"}],"navigatorTitle":[{"text":"VietnameseInput","kind":"identifier"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/LicenseKit":{"type":"topic","kind":"symbol","url":"\/documentation\/vietnameseinput\/licensekit","role":"collection","title":"LicenseKit","abstract":[],"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/LicenseKit"},"mailto:info@kankoda.com":{"titleInlineContent":[{"text":"info@kankoda.com","type":"text"}],"url":"mailto:info@kankoda.com","type":"link","identifier":"mailto:info@kankoda.com","title":"info@kankoda.com"},"https://kankoda.gumroad.com":{"type":"link","url":"https:\/\/kankoda.gumroad.com","title":"Gumroad store","identifier":"https:\/\/kankoda.gumroad.com","titleInlineContent":[{"text":"Gumroad store","type":"text"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInputEngine":{"type":"topic","abstract":[{"type":"text","text":"This Vietnamese input engine can be used simulate typing"},{"type":"text","text":" "},{"type":"text","text":"text with any supported "},{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VietnameseInputEngine"}],"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputEngine","title":"VietnameseInputEngine","kind":"symbol","url":"\/documentation\/vietnameseinput\/vietnameseinputengine","navigatorTitle":[{"kind":"identifier","text":"VietnameseInputEngine"}]},"Logo":{"alt":"Vietnamese Input Logo","variants":[{"url":"\/images\/com.kankoda.VietnameseInput\/Logo.png","traits":["1x","light"]}],"type":"image","identifier":"Logo"},"https://techhub.social/@kankoda":{"type":"link","url":"https:\/\/techhub.social\/@kankoda","title":"@kankoda@techhub.social","identifier":"https:\/\/techhub.social\/@kankoda","titleInlineContent":[{"text":"@kankoda@techhub.social","type":"text"}]},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInputVersionString":{"fragments":[{"text":"VietnameseInputVersionString","kind":"identifier"}],"url":"\/documentation\/vietnameseinput\/vietnameseinputversionstring","abstract":[{"text":"Project version string for VietnameseInput.","type":"text"}],"title":"VietnameseInputVersionString","role":"symbol","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputVersionString","type":"topic","kind":"symbol"},"https://bsky.app/profile/kankoda.bsky.social":{"titleInlineContent":[{"text":"@kankoda.bsky.social","type":"text"}],"url":"https:\/\/bsky.app\/profile\/kankoda.bsky.social","type":"link","identifier":"https:\/\/bsky.app\/profile\/kankoda.bsky.social","title":"@kankoda.bsky.social"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput":{"title":"VietnameseInput","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput","role":"collection","abstract":[{"type":"text","text":"Add Vietnamese input to your apps on all major Apple platforms."}],"url":"\/documentation\/vietnameseinput","kind":"symbol","type":"topic"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Getting-Started-Article":{"url":"\/documentation\/vietnameseinput\/getting-started-article","type":"topic","role":"article","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Getting-Started-Article","abstract":[{"text":"This guide describes how to get started with VietnameseInput.","type":"text"}],"kind":"article","title":"Getting Started"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Swift":{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Swift","type":"topic","title":"Swift","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/vietnameseinput\/swift"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/Vietnamese/InputMethod":{"identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Vietnamese\/InputMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputMethod"}],"abstract":[{"type":"text","text":"This enum defines available Vietnamese input methods."}],"url":"\/documentation\/vietnameseinput\/vietnamese\/inputmethod","kind":"symbol","role":"symbol","title":"Vietnamese.InputMethod","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputMethod"}]},"https://kankoda.com":{"titleInlineContent":[{"text":"Kankoda","type":"text"}],"url":"https:\/\/kankoda.com","type":"link","identifier":"https:\/\/kankoda.com","title":"Kankoda"},"doc://com.kankoda.VietnameseInput/documentation/VietnameseInput/VietnameseInputVersionNumber":{"role":"symbol","identifier":"doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputVersionNumber","type":"topic","title":"VietnameseInputVersionNumber","abstract":[{"type":"text","text":"Project version number for VietnameseInput."}],"kind":"symbol","url":"\/documentation\/vietnameseinput\/vietnameseinputversionnumber","fragments":[{"kind":"identifier","text":"VietnameseInputVersionNumber"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/Getting-Started-Article"],"anchor":"Articles"},{"title":"Variables","generated":true,"identifiers":["doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputVersionNumber","doc:\/\/com.kankoda.VietnameseInput\/documentation\/VietnameseInput\/VietnameseInputVersionString"],"anchor":"Variables"}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null}]}]}